### ISSUE TITLE
Attempted to redefine property directionalLockEnabled error

### ISSUE THREAD

**Issue by ojaspatwardhan** [andyfenelon/react-native-UIKit#2]
After running my application i am getting this syntax error

**Comment by andyfenelon** [comment]
do you have any more info? eg which components you were using.

**Comment by guns2410** [comment]
Hi, facing the same error message. I am trying to use LoginForm component.

**Comment by andyfenelon** [comment]
thanks i'm going to have a look at this package over the weekend.
