### ISSUE TITLE
Error - Only one default export allowed per module

### ISSUE THREAD

**Issue by yogieputra8** [andyfenelon/react-native-UIKit#4]
Hi,

So I just clone and do some stuff with this kits,
I get some error when compiled to iOS simulator
[![Screen Shot 2016-08-26 at 9.32.39 AM.png](https://s12.postimg.org/pzjqx7oal/Screen_Shot_2016_08_26_at_9_32_39_AM.png)](https://postimg.org/image/m36f183ax/)
[![Screen Shot 2016-08-26 at 9.32.51 AM.png](https://s3.postimg.org/f1sps5gsj/Screen_Shot_2016_08_26_at_9_32_51_AM.png)](https://postimg.org/image/gtlon205b/)

My package.json dependencies:
```
"dependencies": {
    "react": "15.3.1",
    "react-native": "0.32.0",
    "react-native-uikit": "^0.1.0"
  }
```

Solutions:
In the `YOUR-APP/node_modules/react-native-uikit/lib/login-form/index.js`
at the end of the code, line 89, give comment marks to this code:
`export default LoginForm;`
become this
`//export default LoginForm;`

**Comment by jjzazuet** [comment]
Hi. I have the same problem with Android. Thanks!

**Comment by andyfenelon** [comment]
good spot, should be good now. but i'm going to have a proper look at the package over the weekend.

**Comment by andyfenelon** [comment]
should be good now.
